### ISSUE TITLE
bdb file in /var/lib/ldap owned by root after prepopulation

### ISSUE THREAD

**Issue by SocketErr** [dinkel/docker-openldap#10]
When using the prepopulation functionality, the resulting bdb file in the /var/lib/ldap directory is owned by "root" and not "openldap".

**Comment by dinkel** [comment]
Did try a to reproduce what you have been describing, but the files I see, are all owned by "openldap" as desired (with a small prepopulate LDIF, that does get loaded).

See here:

```
root@3829a4abd718:/var/lib/ldap# ls -lsa
total 740
  4 drwxr-xr-x  2 openldap openldap     4096 Jun 26 21:06 .
  4 drwxr-xr-x 16 root     root         4096 Jun 26 21:06 ..
  4 -rw-r--r--  1 openldap openldap       96 Jun 26 21:06 DB_CONFIG
376 -rw-------  1 openldap openldap   589823 Jun 26 21:06 __db.001
144 -rw-------  1 openldap openldap   147455 Jun 26 21:06 __db.002
 80 -rw-------  1 openldap openldap   114687 Jun 26 21:06 __db.003
  4 -rw-r--r--  1 openldap openldap     2048 Jun 26 21:06 alock
  8 -rw-------  1 openldap openldap     8192 Jun 26 21:06 cn.bdb
  8 -rw-------  1 openldap openldap     8192 Jun 26 21:06 dn2id.bdb
 32 -rw-------  1 openldap openldap    32768 Jun 26 21:06 id2entry.bdb
 68 -rw-------  1 openldap openldap 10485759 Jun 26 21:06 log.0000000001
  8 -rw-------  1 openldap openldap     8192 Jun 26 21:06 objectClass.bdb
```

Could you give some more information on what you did and how to reproduce the error?

**Comment by SocketErr** [comment]
Here is the "docker run" command I'm using to stand up the container:

```
docker run --name test-ldap -d -e SLAPD_PASSWORD=password -e SLAPD_DOMAIN=test.com -p 389:
389 -v /c/ldap:/etc/ldap.dist/prepopulate dinkel/openldap
```

Here is a simple prepopulate LDIF I put together:  [http://pastebin.com/ngJX7LWT](http://pastebin.com/ngJX7LWT)

When I create the container, using the above command and LDIF, my /var/lib/ldap directory looks like this:

```
root@7515a4592186:/# cd /var/lib/ldap
root@7515a4592186:/var/lib/ldap# ls -l
total 564
-rw-r--r-- 1 openldap openldap       96 Jun 27 03:42 DB_CONFIG
-rw------- 1 openldap openldap   294911 Jun 27 03:42 __db.001
-rw------- 1 openldap openldap   139263 Jun 27 03:42 __db.002
-rw------- 1 openldap openldap   114687 Jun 27 03:42 __db.003
-rw-r--r-- 1 openldap openldap     2048 Jun 27 03:42 alock
-rw------- 1 openldap openldap     8192 Jun 27 03:42 cn.bdb
-rw------- 1 openldap openldap     8192 Jun 27 03:42 dn2id.bdb
-rw------- 1 openldap openldap    32768 Jun 27 03:42 id2entry.bdb
-rw------- 1 openldap openldap 10485759 Jun 27 03:42 log.0000000001
-rw------- 1 openldap openldap     8192 Jun 27 03:42 objectClass.bdb
-rw------- 1 root     root         8192 Jun 27 03:42 uid.bdb
root@7515a4592186:/var/lib/ldap#
```

**Comment by dobos** [comment]
I had problem running it on a file system with acl. It would be worth resetting file permission and ownership of /etc/ldap to openldap

**Comment by dinkel** [comment]
@SocketErr: Thanks a lot! I could now reproduce the problem with your prepopulate LDIF (contrarily to mine, it did create entries inside a new group, that then created the additional `[groupname].bdb` file). Fixing it was then just a matter of updateing the file ownerships later in the `entrypoint.sh` processing.

@dobos: With commit https://github.com/dinkel/docker-openldap/commit/d168f143c057b0fe34a5bd21356e19d1fe0d8c4c I tried to fix your problem as well (however **not** by changing the ownership of the configuration files to 'openldap', because I think it would be wrong). In case your your issue is not fixed, I would like to ask you to open another issue.

Thanks to both of you in helping to make this Docker image better!
