### ISSUE TITLE
Update docker hub 2.4.x tags along with latest?

### ISSUE THREAD

**Issue by danhawkes** [dinkel/docker-openldap#15]
Hi,
I just noticed that the `2.4.x` tags on docker hub are quite a way behind `latest`. 

It looks like you've adopted the openldap version for the container, seeing as there's several `2.4.x` tags. As changes here aren't factored into the docker hub tag, do you think it'd make sense to update those tags along with latest?

**Comment by jlk** [comment]
FYI I've forked this project with intent to provide better tagging on Images. Take a look at https://hub.docker.com/r/jlkinsel/openldap/ - open to comments/suggestions.
