### ISSUE TITLE
Debian jessie base image is now oldstable

### ISSUE THREAD

**Issue by fedde-s** [dinkel/docker-openldap#24]
The documentation for this image falsely states that it builds on Debian stable, as it instead pulls in the oldstable (jessie) release next to the stable (stretch) release that is used by more recent images. Could the word ‘stable’ be removed from the documentation until it upgrades to stretch?

**Comment by fedde-s** [comment]
Some images on Docker Hub have separate Dockerfiles/images tagged with `-stretch`, if you don't want to break compatibility for people who use your image to do other things than the default command.

**Comment by dinkel** [comment]
With merging pull request #25, this container now runs "stable" again. As there seem to be no compatibility issues, I don't see a point in creating different branches for different base image versions (yet).
