### ISSUE TITLE
Launch with LDIF data set

### ISSUE THREAD

**Issue by jmkgreen** [dinkel/docker-openldap#9]
Would this be possible? My use-case:

Need to launch the container as part of a compose file for integration tests with my software project. The project has an LDIF file holding the data entries (users, organisations, etc). I just cannot launch this and get this LDIF file in at the same time.

**Comment by dinkel** [comment]
Currently this container does not have any kind of pre-seed / data bootstrap mechanism.

Your use case tells me that there is a valid reason to have something like that.

I will try to implement it in the next few days.

**Comment by dinkel** [comment]
Hi @jmkgreen,

With commit cfc8831425d59632033347cfcb057c5ca3d56bef I added a prepopulation functionality (described in the README). It would be great if you could try it out and give feedback.

Thanks,

Dinkel

**Comment by dinkel** [comment]
No feedback received, therefore considering this enhancement as integrated.
